language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy
install:
  - pip uninstall -y nose
  - pip install -r requirements.txt --use-mirrors
script:
  - python setup.py build_tests || python setup.py egg_info; python selftest.py
