# database location
# Upadate all database locations

databases: /home/AMED/dereje.jima/databases
human_dna: /home/AMED/dereje.jima/databases/humandna/human_dna
h_sapiens_rna: /home/AMED/dereje.jima/databases/humanrna/h_sapiens_rna
nt_db:  /home/AMED/dereje.jima/databases/ncbi/blast/nt/nt
tax_nodes: /home/AMED/dereje.jima/databases/ncbi/taxonomy/nodes.dmp
tax_names: /home/AMED/dereje.jima/databases/ncbi/taxonomy/names.dmp

#paired end lane to run
blast_unassembled: 1000
R1: /media/VD_Research/People/Dereje.Jima/2014_programming/python/usamriidPathDiscov/testData/F.fastq  #update this line to the location of F.fastq (name of fastq doesn't matter)
R2: /media/VD_Research/People/Dereje.Jima/2014_programming/python/usamriidPathDiscov/testData/R.fastq  #update this line to the location of R.fastq (name of fastq doesn't matter



